---
title: "Visualizing Cricket World Cup 2019 Boundaries"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[< Back to main website](https://sajibdevnath.github.io/visualisation.html)

  
> Mission: Visualizing Cricket World Cup 2019 Boundaries


Importing required libraries:
`ggplot2`, `dplyr`,`tidyr`,`ggthemes`,`ggdark`


Importing Data:

```{r}
world_cup_boundaries <- read.csv('data/world_cup_boundary.csv')
str(world_cup_boundaries)
```

Tidy the data for analysis:

```{r, warning = FALSE, message = FALSE}
library(tidyr)
library(dplyr)
wcb_tidy <- world_cup_boundaries %>% 
  select(Name, Six, Four) %>% 
  gather(Boundary, Total, -Name)
```

Visualising with ggplot:

```{r, warning = FALSE, message = FALSE}
library(ggplot2)
library(ggthemes)
library(ggdark)
ggplot(wcb_tidy, aes(reorder(Name, Total), Total, fill = Boundary)) +
  geom_bar(stat = 'identity', width = .7) +
  coord_flip() +
  dark_theme_minimal(base_family = "Helvetica", base_size = 20) +
  labs(title = 'World Cup 2019 Boundaries', x = 'Player') +
  scale_fill_excel()
```



